"""Generate the jeep course assets.

Everything is produced from code rather than shipped as a binary, so the
terrain is reproducible, reviewable in a diff, and small. Regenerate with
`python3 harness/make_assets.py`; the output is deterministic.
"""

import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets")

# The course runs along +z, matching the axis convention PhysX's own vehicle
# snippets use: z longitudinal, x lateral, y vertical. The first stretch is
# flat so a vehicle has somewhere to settle and prove it is stable before
# anything is asked of it.
FLAT_UNTIL = 12.0
RAMP_START, RAMP_PEAK, RAMP_END = 26.0, 32.0, 38.0
RAMP_HEIGHT = 1.4


def height(x, z):
    """x is lateral, z runs along the course."""
    h = 0.0
    if z > FLAT_UNTIL:
        # gentle rolling ground, small enough not to unsettle a sane vehicle
        t = (z - FLAT_UNTIL)
        h += 0.18 * math.sin(t * 0.22) + 0.12 * math.sin(x * 0.31 + 1.1)
    if RAMP_START <= z <= RAMP_END:
        # a symmetric ramp: up, over, down
        if z <= RAMP_PEAK:
            u = (z - RAMP_START) / (RAMP_PEAK - RAMP_START)
        else:
            u = (RAMP_END - z) / (RAMP_END - RAMP_PEAK)
        h += RAMP_HEIGHT * (u * u * (3 - 2 * u))
    if 48.0 <= z <= 62.0:
        # a cross slope, so a vehicle that corners badly rolls here
        h += 0.10 * (x + 9.0)
    return h


def terrain(path, x0=-10.0, x1=10.0, z0=-8.0, z1=76.0, step=0.8):
    nx = int(round((x1 - x0) / step)) + 1
    nz = int(round((z1 - z0) / step)) + 1
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# probe suite jeep course terrain, generated by harness/make_assets.py\n")
        fh.write("# %d by %d grid, %.2f m spacing, y is up\n" % (nx, nz, step))
        for i in range(nx):
            x = x0 + i * step
            for j in range(nz):
                z = z0 + j * step
                fh.write("v %.4f %.4f %.4f\n" % (x, height(x, z), z))
        for i in range(nx - 1):
            for j in range(nz - 1):
                a = i * nz + j + 1
                b = (i + 1) * nz + j + 1
                c = (i + 1) * nz + (j + 1) + 1
                d = i * nz + (j + 1) + 1
                # counter-clockwise seen from above, so the surface normals
                # point up. PhysX culls backfaces in mesh raycasts, and the
                # suspension is raycast, so a flipped grid is invisible to it.
                fh.write("f %d %d %d\n" % (a, c, b))
                fh.write("f %d %d %d\n" % (a, d, c))
    return nx * nz, (nx - 1) * (nz - 1) * 2


def box(fh, base, cx, cy, cz, sx, sy, sz):
    pts = []
    for dx in (-1, 1):
        for dy in (-1, 1):
            for dz in (-1, 1):
                pts.append((cx + dx * sx / 2, cy + dy * sy / 2, cz + dz * sz / 2))
    for p in pts:
        fh.write("v %.4f %.4f %.4f\n" % p)
    q = [base + i for i in range(1, 9)]
    # 0:(-,-,-) 1:(-,-,+) 2:(-,+,-) 3:(-,+,+) 4:(+,-,-) 5:(+,-,+) 6:(+,+,-) 7:(+,+,+)
    faces = [(0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1),
             (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3)]
    for f in faces:
        fh.write("f %d %d %d\n" % (q[f[0]], q[f[1]], q[f[2]]))
        fh.write("f %d %d %d\n" % (q[f[0]], q[f[2]], q[f[3]]))
    return base + 8


def jeep(path):
    """A boxy jeep for the picture. The physics uses the dimensions, not this."""
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# probe suite jeep, generated by harness/make_assets.py\n")
        fh.write("# origin at the chassis centre of mass, +z forward, +y up\n")
        n = 0
        n = box(fh, n, 0.0, 0.0, 0.0, 1.80, 0.80, 3.80)      # body
        n = box(fh, n, 0.0, 0.62, -0.30, 1.70, 0.62, 1.70)   # cabin
        for wz in (1.35, -1.35):
            for wx in (0.86, -0.86):
                n = box(fh, n, wx, -0.62, wz, 0.30, 0.72, 0.72)  # wheels
    return n


def main():
    os.makedirs(OUT, exist_ok=True)
    v, f = terrain(os.path.join(OUT, "terrain.obj"))
    print("assets/terrain.obj  %d vertices, %d triangles" % (v, f))
    n = jeep(os.path.join(OUT, "jeep.obj"))
    print("assets/jeep.obj     %d vertices" % n)
    print("\nheight along the course centreline:")
    for z in (0, 10, 20, 29, 32, 35, 44, 55, 70):
        print("  z=%-4d y=%.3f" % (z, height(0.0, float(z))))


if __name__ == "__main__":
    main()
