// engine/math/fixed_trig.h
//
// Angle helpers for the simulation.
//
// Angles are turns in Q16: 0x10000 is a full circle, 0x4000 is ninety
// degrees. Turns wrap for free on a signed 32 bit add, which is why the
// simulation stores facings this way rather than in radians.
//
// The sine table is generated offline by tools/gen_trig_table.py, checked in
// as math/trig_table.inc, and never regenerated by the build. It holds one
// quarter turn at 1/4096 turn resolution, and the lookup below interpolates
// between neighbouring entries with a Q16 multiply.

#pragma once

#include <cstdint>

#include "core/types.h"

namespace math {

using core::Q16;
using core::kQ16One;

inline constexpr Q16 kTurn        = 1 << 16;         // one full circle
inline constexpr Q16 kQuarterTurn = 1 << 14;
inline constexpr Q16 kHalfTurn    = 1 << 15;

// Table entries, one quarter turn, Q16 sine values. Defined in
// math/trig_table.inc and pulled in by math/fixed_trig.cpp.
inline constexpr uint32_t kSinTableSize = 4096;
extern const int32_t kSinTableQ16[kSinTableSize + 1];

// Sine and cosine of an angle in turns. Exact on the table entries and
// linearly interpolated between them. The result is in Q16, so kQ16One is 1.0.
Q16 SinTurns(Q16 turns);
Q16 CosTurns(Q16 turns);

// Angle of the vector (x, y) in turns, measured counter clockwise from +x.
// x and y may be any fixed point scale as long as they share one: only the
// ratio matters. Returns a value in [0, kTurn).
Q16 AtanTurns(Q16 y, Q16 x);

// Signed shortest difference from a to b, in the range [-kHalfTurn, kHalfTurn).
// This is just a wrapping subtract, and it is exact.
inline Q16 ShortestDeltaTurns(Q16 from, Q16 to) {
    const int32_t raw = static_cast<int32_t>(static_cast<uint32_t>(to) - static_cast<uint32_t>(from));
    const int32_t wrapped = static_cast<int32_t>(static_cast<uint32_t>(raw) & 0xFFFFu);
    return wrapped >= kHalfTurn ? wrapped - kTurn : wrapped;
}

// Move from towards to by at most max_step turns.
inline Q16 StepTowardsTurns(Q16 from, Q16 to, Q16 max_step) {
    const Q16 delta = ShortestDeltaTurns(from, to);
    if (delta > max_step)  return static_cast<Q16>((from + max_step) & 0xFFFF);
    if (delta < -max_step) return static_cast<Q16>((from - max_step) & 0xFFFF);
    return static_cast<Q16>(to & 0xFFFF);
}

// Degrees per second, as authored by designers, into turns per tick.
inline Q16 DegreesPerSecondToTurnsPerTick(Q16 degrees_per_second) {
    // turns = degrees / 360, per tick = per second / kTickHz.
    const int64_t numerator = static_cast<int64_t>(degrees_per_second) * kTurn;
    return static_cast<Q16>(numerator / (360LL * static_cast<int64_t>(core::kTickHz) * kQ16One / kQ16One));
}

inline Q16 DegreesToTurns(Q16 degrees) {
    return static_cast<Q16>((static_cast<int64_t>(degrees) * kTurn) / (360LL * kQ16One));
}

inline Q16 TurnsToDegrees(Q16 turns) {
    return static_cast<Q16>((static_cast<int64_t>(turns) * 360LL * kQ16One) / kTurn);
}

}  // namespace math
